[package]
name = "mhf-iel-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
mhf-iel = { path = ".."}
serde = { workspace = true }
clap = { version = "4.4.7", features = ["derive"] }
serde_json = "1.0"
